baseURL = "https://ionsat.netlify.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Airspace | Creative Agency Hugo Template"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.footer]]
URL = "project"
name = "Notre Projet"
weight = 1
[[menu.footer]]
URL = "about"
name = "A propos de nous"
weight = 2
[[menu.main]]
URL = "about"
name = "A propos de nous "
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "project"
name = "Notre Projet "
weight = 1
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "demo@email.com"
google_analitycs_id = ""
location = "North Main Street,Brooklyn Australia"
logo = "images/logo.png"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "https://twitter.com/hashtag/IonSat?src=hashtag_click"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com"
